version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: CHANGE_ME 
    volumes:
      - wrath-rs-database:/var/lib/mysql
    ports:
      - "3306:3306"
      

volumes:
  wrath-rs-database:
