[package]
name = "dbc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "*", features = ["attributes"] }
anyhow = { version = "1.0.32" }
podio = { version = "0.2" } 
