name: wrath-rs

on:
  push:
    branches: [ main, github_ci ]
  pull_request:
    branches: [ main, github_ci ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Wrath-rs on stable rust
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build
